In [13]:
!where python

C:\Python312\python.exe
C:\Users\marti\miniconda3\python.exe
C:\Users\marti\AppData\Local\Microsoft\WindowsApps\python.exe

In [27]:
!cond

^C

In [16]:
import pandas as pd

In [52]:
df=pd.read_excel('C:/Users/marti/Downloads/proyecciones-poblacion-bogota-desagreacion2024.xlsx',
                sheet_name='UPZ Bogota 2018_2024')
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"PROYECCIONES DE POBLACIÓN DE BOGOTÁ POR UPZ, S...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PROYECCIONES DE POBLACIÓN DE BOGOTÁ POR UPZ. P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,CAPELLANIA,2024,115,09,415,403,472,504,710,830,...,538,342,261,104,46,9,7,8631,9984,18615
789,ALAMOS,2024,116,10,198,289,330,392,452,610,...,286,208,104,64,20,2,5,5684,6411,12095
790,AEROPUERTO EL DORADO,2024,117,09,11,14,10,179,94,98,...,12,13,2,2,1,3,0,608,292,900
791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
792,Fuente: DANE.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
df = df[df['Unnamed: 1'].isna()==False]
df.columns = list(df.iloc[0,])
df = df.iloc[1:,]
df

,AREA GEOGRÁFICA,AÑO,UPZ,LOC,Hombres_0-4,Hombres_5-9,Hombres_10-14,Hombres_15-19,Hombres_20-24,Hombres_25-29,...,Total_70-74,Total_75-79,Total_80-84,Total_85-89,Total_90-94,Total_95-99,Total_100+,Total_Hombres,Total_Mujeres,Total
7,PASEO DE LOS LIBERTADORES,2018,001,01,84,94,75,128,138,129,...,55,22,18,8,5,2,4,1279,1288,2567
8,LA ACADEMIA,2018,002,11,125,203,216,207,154,82,...,49,22,16,9,9,2,9,1997,2110,4107
9,GUAYMARAL,2018,003,11,31,76,115,129,91,42,...,25,21,11,10,10,1,4,996,1069,2065
10,VERBENAL,2018,009,01,4162,4103,4183,4558,6019,5846,...,1994,1156,672,307,150,71,44,56578,62502,119080
11,LA URIBE,2018,010,01,929,850,968,1073,1211,1114,...,711,449,248,129,76,43,24,14327,16867,31194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
786,BAVARIA,2024,113,08,717,1096,1054,1115,1300,1604,...,1345,852,544,255,131,54,24,19573,21883,41456
787,MODELIA,2024,114,09,843,907,1003,1140,1459,1707,...,1847,1347,866,470,202,83,45,20672,24805,45477
788,CAPELLANIA,2024,115,09,415,403,472,504,710,830,...,538,342,261,104,46,9,7,8631,9984,18615
789,ALAMOS,2024,116,10,198,289,330,392,452,610,...,286,208,104,64,20,2,5,5684,6411,12095
790,AEROPUERTO EL DORADO,2024,117,09,11,14,10,179,94,98,...,12,13,2,2,1,3,0,608,292,900

In [57]:
len(df['AREA GEOGRÁFICA'].unique())

112

In [55]:
grouped_df = df.groupby(['AREA GEOGRÁFICA','AÑO','UPZ','LOC']).sum()
grouped_df

                              Hombres_0-4  Hombres_5-9  Hombres_10-14  \
AREA GEOGRÁFICA AÑO  UPZ LOC
20 DE JULIO     2018 034 04          2575         2595           2702
                2019 034 04          2642         2596           2648
                2020 034 04          2679         2579           2585
                2021 034 04          2762         2538           2516
                2022 034 04          2837         2512           2452
...                                   ...          ...            ...
ZONA INDUSTRIAL 2020 108 16           210          226            246
                2021 108 16           214          227            245
                2022 108 16           219          227            249
                2023 108 16           225          228            247
                2024 108 16           230          228            245

                              Hombres_15-19  Hombres_20-24  Hombres_25-29  \
AREA GEOGRÁFICA AÑO  UPZ LOC
20 DE JULIO     2018 034 04            3163           3918           3714
                2019 034 04            3069           3883           3822
                2020 034 04            3003           3769           3919
                2021 034 04            2913           3645           4006
                2022 034 04            2822           3521           4005
...                                     ...            ...            ...
ZONA INDUSTRIAL 2020 108 16             270            361            315
                2021 108 16             268            353            327
                2022 108 16             266            336            335
                2023 108 16             265            321            338
                2024 108 16             263            303            335

                              Hombres_30-34  Hombres_35-39  Hombres_40-44  \
AREA GEOGRÁFICA AÑO  UPZ LOC
20 DE JULIO     2018 034 04            3181           2733           2180
                2019 034 04            3271           2778           2219
                2020 034 04            3351           2790           2309
                2021 034 04            3424           2811           2370
                2022 034 04            3468           2815           2410
...                                     ...            ...            ...
ZONA INDUSTRIAL 2020 108 16             298            254            219
                2021 108 16             312            264            230
                2022 108 16             322            271            242
                2023 108 16             335            278            253
                2024 108 16             345            290            258

                              Hombres_45-49  ...  Total_70-74  Total_75-79  \
AREA GEOGRÁFICA AÑO  UPZ LOC                 ...
20 DE JULIO     2018 034 04            2148  ...         1807         1200
                2019 034 04            2111  ...         1857         1250
                2020 034 04            2084  ...         1932         1303
                2021 034 04            2069  ...         1992         1344
                2022 034 04            2090  ...         2091         1414
...                                     ...  ...          ...          ...
ZONA INDUSTRIAL 2020 108 16             177  ...          122           78
                2021 108 16             181  ...          127           79
                2022 108 16             188  ...          135           84
                2023 108 16             194  ...          146           88
                2024 108 16             205  ...          155           90

                              Total_80-84  Total_85-89  Total_90-94  \
AREA GEOGRÁFICA AÑO  UPZ LOC
20 DE JULIO     2018 034 04           769          428          197
                2019 034 04           807          454          204
                2020 034 04           853          476          208
                2021 034 04           880          483          204
                2022 034 04           960          514          224
...                                   ...          ...          ...
ZONA INDUSTRIAL 2020 108 16            44           21            9
                2021 108 16            46           22            9
                2022 108 16            49           24           10
                2023 108 16            50           25           10
                2024 108 16            51           25            9

                              Total_95-99  Total_100+  Total_Hombres  \
AREA GEOGRÁFICA AÑO  UPZ LOC
20 DE JULIO     2018 034 04            63          18          37998
                2019 034 04            67          17          38381
                2020 034 04            67          15          38639
                2021 034 04            54          16          38752
                2022 034 04            73          16          38881
...                                   ...         ...            ...
ZONA INDUSTRIAL 2020 108 16             5           1           3194
                2021 108 16             5           2           3264
                2022 108 16             6           2           3329
                2023 108 16             7           2           3383
                2024 108 16             6           2           3425

                              Total_Mujeres  Total
AREA GEOGRÁFICA AÑO  UPZ LOC
20 DE JULIO     2018 034 04           40363  78361
                2019 034 04           40892  79273
                2020 034 04           41282  79921
                2021 034 04           41611  80363
                2022 034 04           41774  80655
...                                     ...    ...
ZONA INDUSTRIAL 2020 108 16            3162   6356
                2021 108 16            3221   6485
                2022 108 16            3252   6581
                2023 108 16            3283   6666
                2024 108 16            3303   6728

[784 rows x 66 columns]

In [72]:
import geopandas as gpd
import pandas as pd

In [77]:
upzs = gpd.read_file('C:/Users/marti/Downloads/poblacion-upz-bogota.geojson')
upzs

ImportError: The 'read_file' function requires the 'pyogrio' or 'fiona' package, but neither is installed or imports correctly.
Importing fiona resulted in: DLL load failed while importing _env: The specified procedure could not be found.
Importing pyogrio resulted in: No module named 'pyogrio'